import {ServerMetadata} from '../api/ServerMetadata';

/**
 * Transform a model object to and from the OpenNMS server's model.
 */
export interface IModelSerializer<T> {
    /**
     * Transforms JSON data (including JSON generated by X2JS) from OpenNMS to a model object.
     *
     * @param {object} json The JSON object to transform to a model object.
     * @return {T} The transformed model object.
     */
    fromJson(json: object): T;

    /**
     * Transforms the model object to a JSON object suitable for POSTing to OpenNMS.
     *
     * @param {T} model The model object to transform to JSON.
     * @returns {object} The model object as a POSTable JSON object.
     */
    toJson(model: T): object;

    /**
     * Transforms the model object to XML suitable for POSTing to OpenNMS.
     *
     * @param {T} model The model object to transform to XML.
     * @returns {string} The model object as an XML string.
     */
    toXml(model: T): string;
}
